CREATE TABLE Code.Expediente(Id_expendiente INT AUTO_INCREMENT NOT NULL, 
Matricula VARCHAR(255) NOT NULL,
Calle VARCHAR(255) NOT NULL,
Colonia VARCHAR(255) NOT NULL,
Numero VARCHAR(255) NOT NULL,
Cp VARCHAR(255) NOT NULL,
Id_Incidencia INT NOT NULL, PRIMARY KEY (Id_expendiente)
)ENGINE=InnoDB